export const HomeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Bank",
  headline: "Unlimited Transactions with Zero Fees",
  description: "Get access",
  buttonLabel: "Get started",
  imgStart: true,
  img: require("../../images/svg-1.svg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const HomeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Unlimted Access",
  headline: "Unlimited Transactions with Zero Fees",
  description: "Get access",
  buttonLabel: "Learn More",
  imgStart: true,
  img: require("../../images/svg-1.svg"),
  alt: "Piggy",
  dark: false,
  primary: false,
  darkText: true,
};

export const HomeObjThree = {
  id: "signup",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Bank",
  headline: "Unlimited Transactions with Zero Fees",
  description: "Get access",
  buttonLabel: "Get started",
  imgStart: true,
  img: require("../../images/svg-1.svg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};
